version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch1
    environment:
      - discovery.type=single-node
      - discovery.seed_hosts=elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    container_name: kibana1
    ports:
      - 5601:5601
    networks:
      - elastic
  redis:
    image: redis
    container_name: redis1
    ports:
      - 1453:6379
    networks:
      - elastic

networks:
  elastic:
    driver: bridge